module.exports = {
  UserScreenIcon: {
    BgImg: require('../../assets/images/bg_new_img.png'),
    Applogo: require('../../assets/images/logo.png'),
    BarberIcon: require('../../assets/images/barber1.png'),
    BarbersIcon: require('../../assets/images/scissors.png'),

    CustomerIcon: require('../../assets/images/barber2.png'),
    Applogo1: require('../../assets/images/BarChoose.png'),
    Applogo2: require('../../assets/images/CusChoose.png'),
  },
  JoinAsBarberIcon: {
    BgBarberImg: require('../../assets/images/dark3x.png'),
  },
  SignUpIcon: {
    BgImg: require('../../assets/images/signup-bg.png'),
    BackArrow: require('../../assets/images/backIcon.png'),
    User: require('../../assets/images/user.png'),
    Password: require('../../assets/images/password.png'),
    Email: require('../../assets/images/email.png'),
    Mobile: require('../../assets/images/mobile.png'),
    Eye: require('../../assets/images/view.png'),
    CloseEye: require('../../assets/images/notview.png'),
    Fb: require('../../assets/images/facbook.png'),
    Twitter: require('../../assets/images/twitter.png'),
    Google: require('../../assets/images/google.png'),
    Instagram: require('../../assets/images/instagram.png'),
    Pintrest: require('../../assets/images/pintrest.png'),
  },
  ProfileBuildIcon: {
    Camera: require('../../assets/images/camera.png'),
    Gallery: require('../../assets/images/gallery.png'),
    Default: require('../../assets/images/default.png'),
    Plus: require('../../assets/images/addFill.png'),
    ProfileBackground: require('../../assets/images/profilesetup.png'),
    Off: require('../../assets/images/off.png'),
    On: require('../../assets/images/on.png'),
  },
  WelcomeIcon: {
    EasyBooking: require('../../assets/images/easy-booking.png'),
    InviteFriend: require('../../assets/images/invite-friends.png'),
    Portfolio: require('../../assets/images/portfolio.png'),
    PreBenefit: require('../../assets/images/premium-benefit.png'),
  },
  HomeIcon: {
    Filter: require('../../assets/images/filter.png'),
    RedBg: require('../../assets/images/red-bg.png'),
    EditIcon: require('../../assets/images/edit.png'),
    NotifyIcon: require('../../assets/images/notification.png'),
    OffNotifyIcon: require('../../assets/images/Bell.png'),
    CustomerBlackBg: require('../../assets/images/BlackBg.png'),
    CustomerBlackBgLogo: require('../../assets/images/Hairbiddy2.png'),
    HomeBgLogo3: require('../../assets/images/Hairbiddy3.png'),
    StylistRedBg: require('../../assets/images/RedBg.png'),
    StylistRedBgLogo: require('../../assets/images/Hairbiddy.png'),
  },
  Notification: {
    BackArrow: require('../../assets/images/left-arrow.png'),
  },

  StylistTemplate: {
    TemplateOne: require('../../assets/images/temp_one.png'),
    TemplateTwo: require('../../assets/images/temp_two.png'),
    Rating: require('../../assets/images/rating.png'),
  },

  StaticPage: {
    AboutUs: require('../../assets/images/aboutUs.png'),
    Copy: require('../../assets/images/copy.png'),
    LogoTwo: require('../../assets/images/logo_two.png'),
    LogoThree: require('../../assets/images/logo_three.png'),
  },
  Appointment: {
    DownArrow: require('../../assets/images/down.png'),
    UpArrow: require('../../assets/images/up.png'),
    Clock: require('../../assets/images/clock.png'),
    Calendar: require('../../assets/images/calendar.png'),
    Shop: require('../../assets/images/shop.png'),
    ShopAddress: require('../../assets/images/shopaddreess.png'),
    ShopDateTime: require('../../assets/images/shopdate-and-time.png'),
    Stamp: require('../../assets/images/stamp-paid.png'),
    Phone: require('../../assets/images/phone.png'),
    DotMenu: require('../../assets/images/dot_menu.png'),
    MsgBox: require('../../assets/images/msg_box.png'),
  },
  Haicut: {
    Haircut1: require('../../assets/images/haircut/haircut1.png'),
    Haircut5: require('../../assets/images/haircut/haircut8.png'),
  },
  ProfileIcon: {
    About: require('../../assets/images/profileIcon/AboutUs.png'),
    MapPin: require('../../assets/images/profileIcon/mapPin.png'),
    Edit: require('../../assets/images/profileIcon/Edit.png'),
    Account: require('../../assets/images/profileIcon/AccountSettings.png'),
    Appointment: require('../../assets/images/profileIcon/AppointmentSettings.png'),
    Arrow: require('../../assets/images/profileIcon/arrow.png'),
    Invite: require('../../assets/images/profileIcon/InviteaFriend.png'),
    Logout: require('../../assets/images/profileIcon/logout.png'),
    Payment: require('../../assets/images/profileIcon/PaymentInformation.png'),
    Portfolio: require('../../assets/images/profileIcon/Portfolio.png'),
    Privacy: require('../../assets/images/profileIcon/PrivacyPolicy.png'),
    Salon: require('../../assets/images/profileIcon/SalonSettings.png'),
    Service: require('../../assets/images/profileIcon/ServiceSettings.png'),
    Shop: require('../../assets/images/profileIcon/ShopSettings.png'),
    Subscription: require('../../assets/images/profileIcon/Subscriptions.png'),
    EditIcon: require('../../assets/images/blackEdit.png'),
    Template: require('../../assets/images/profileIcon/TemplateSetting.png'),
    Invoice: require('../../assets/images/profileIcon/Invoice.png'),
    Screen1: require('../../assets/images/Screen1.png'),
    Screen2: require('../../assets/images/Screen2.png'),
    AddFill: require('../../assets/images/addFill.png'),
    Card: require('../../assets/images/profileIcon/card.png'),
  },
  ServiceIcon: {
    Add: require('../../assets/images/add.png'),
    Edit: require('../../assets/images/edits.png'),
    Delete: require('../../assets/images/delete.png'),
    Discount: require('../../assets/images/discount.png'),
    Check: require('../../assets/images/checked.png'),
    Uncheck: require('../../assets/images/uncheck.png'),
  },
  InvoiceIcon: {
    Search: require('../../assets/images/search.png'),
  },
  Portfolio: {
    Plus: require('../../assets/images/plus.png'),
    Upload: require('../../assets/images/Upload.png'),
    Delete: require('../../assets/images/viewdelete.png'),
    Photo: require('../../assets/images/viewphoto.png'),
    Tags: require('../../assets/images/viewtag.png'),
    Close: require('../../assets/images/close.png'),
    Tag: require('../../assets/images/tag.png'),
    Like: require('../../assets/images/customerIcon/portfoliophotolike.png'),
    DisLike: require('../../assets/images/customerIcon/portfoliophotodislike.png'),
  },
  Subscription: {
    FreePlanBg: require('../../assets/images/skyblue.png'),
    PaidPlanBg: require('../../assets/images/paidPlanBg.png'),
    FreeBadge: require('../../assets/images/free.png'),
    PremiumBadge: require('../../assets/images/premium-badge.png'),
    RedCheck: require('../../assets/images/check.png'),
    CircleCheck: require('../../assets/images/uncheckCircle.png'),
    GrayCheck: require('../../assets/images/gray.png'),
    Sub1: require('../../assets/images/sub1.png'),
    Sub2: require('../../assets/images/sub2.png'),
  },
  CustomerHomeIcon: {
    MyPhoto: require('../../assets/images/profileIcon/Portfolio.png'),
    Camera: require('../../assets/images/customerIcon/camera.png'),
    Close: require('../../assets/images/customerIcon/close.png'),
    Gallery: require('../../assets/images/customerIcon/gallery.png'),
    Like: require('../../assets/images/customerIcon/like2.png'),
    MyPhoto2: require('../../assets/images/customerIcon/myphoto.png'),
    American: require('../../assets/images/customerIcon/American.png'),
    LoadingImg: require('../../assets/images/customerIcon/loadgif.gif'),
    Master: require('../../assets/images/customerIcon/mastercard.png'),
    Paypal: require('../../assets/images/customerIcon/paypal.png'),
    Visa: require('../../assets/images/customerIcon/visalogo.png'),
    SalonBg: require('../../assets/images/customerIcon/salonBg2.jpg'),
    BgImage: require('../../assets/images/bg.png'),
    Default: require('../../assets/images/defaultImg.png'),
    NoProfilePic: require('../../assets/images/noprofile.jpg'),
    Remove: require('../../assets/images/remove.png'),
  },
  StylistIcon: {
    Message: require('../../assets/images/customerIcon/message.png'),
    Like: require('../../assets/images/customerIcon/like.png'),
    Rating: require('../../assets/images/customerIcon/rating.png'),
    Review: require('../../assets/images/customerIcon/stylistreview.png'),
    Star: require('../../assets/images/customerIcon/star.png'),
    Star3: require('../../assets/images/fav.png'),
    Star2: require('../../assets/images/customerIcon/star2.png'),
    LocationPin: require('../../assets/images/customerIcon/mappin.png'),
    LocationPin1: require('../../assets/images/customerIcon/blackpin.png'),

    RateStylist: require('../../assets/images/customerIcon/feedbackicon.png'),
    Filter: require('../../assets/images/customerIcon/filter.png'),
    Search: require('../../assets/images/customerIcon/Search.png'),
    Direction: require('../../assets/images/customerIcon/direction.png'),
  },
};
