import {StyleSheet, Dimensions, Platform} from 'react-native';
import {Fonts, Colors} from '../../../constants';
const {height, width} = Dimensions.get('window');

export default StyleSheet.create({
  backgroundStyle: {
    height: Platform.OS === 'android' ? height / 3 + 20 : height / 4 + 20,
    width,
    borderBottomLeftRadius: 15,
    borderBottomRightRadius: 15,
  },
  loadingStyle: {
    backgroundColor: Colors.Red,
    width: 130,
    height: 60,
    display: 'flex',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  cashStyle: {
    width: '70%',
    color: Colors.LightBlack,
    fontSize: 14,
    padding: 10,
    fontFamily: Fonts.Lato_Black,
  },
  profileCard: {
    width: '90%',
    backgroundColor: '#ffffff',
    alignSelf: 'center',
    borderRadius: 15,
    marginBottom: 30,
    marginTop: Platform.OS === 'android' ? -130 : -120,
  },
  notifyCont: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: Platform.OS === 'android' ? 50 : 60,
    width: '90%',
    alignSelf: 'center',
  },
  welcomeName: {
    fontSize: 18,
    color: Colors.White,
    fontFamily: Fonts.HeveticaNowText_Medium,
  },
  inputCont: {
    display: 'flex',
    flexDirection: 'column',
    margin: 30,
    marginTop: 10,
    marginBottom: 20,
    justifyContent: 'space-between',
  },
  labelStyle: {
    fontSize: 13,
    marginTop: 15,
    fontFamily: Fonts.Lato_Semibold,
  },
  textStyle: {
    width: '90%',
    marginLeft: 10,
    fontFamily: Fonts.Lato_Bold,
    fontSize: 13,
    alignSelf: 'center',
  },
  selectorStyle: {
    alignSelf: 'center',
    width: '80%',
    marginTop: 20,
  },
  payContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: Colors.Pink,
    height: 50,
    borderRadius: 10,
    marginTop: 20,
  },
  bContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderColor: '#222B4599',
    borderWidth: 2,
    height: 50,
    borderRadius: 10,
    marginTop: 20,
  },
  b2Container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    backgroundColor: '#191514',
    borderWidth: 2,
    height: 50,
    borderRadius: 10,
    marginTop: 10,
  },
  buttonCont: {
    width: '95%',
    display: 'flex',
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginTop: 30,
    marginBottom: 40,
  },
  buttonStyle: {
    width: 130,
    height: 60,
    display: 'flex',
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  buttonText: {
    fontSize: 16,
    color: Colors.White,
    fontFamily: Fonts.Lato_Heavy,
  },
  rightBorder: {
    height: 20,
    width: 1,
    margin: 5,
    backgroundColor: Colors.LightBlack,
  },
  datetimeStyle: {
    marginTop: 0,
    fontFamily: Fonts.Lato_Bold,
    fontSize: 13,
    alignSelf: 'center',
  },
  inputStyle: {
    display: 'flex',
    alignSelf: 'center',
    width: '100%',
    justifyContent: 'flex-start',
    flexDirection: 'row',
    padding: 20,
    paddingBottom: 0,
    paddingLeft: 0,
  },
  priceText: {
    marginLeft: 15,
    fontFamily: Fonts.Lato_Bold,
    fontSize: 13,
    alignSelf: 'center',
  },
  messText: {
    fontFamily: Fonts.Lato_Bold,
    fontSize: 13,
    color: Colors.LightBlack,
    textAlign: 'center',
    padding: 35,
    paddingTop: 20,
  },
});
